### ISSUE TITLE
add example of custom deployment bucket name to serverless.yml.example

### ISSUE THREAD

**Issue by philvarner** [stac-utils/stac-server#288]
serverless allows you to specify the name of the deployment bucket explicitly. This can be useful if a user wants to have a known name for the bucket or to set attributes on it like block public access.

npm install serverless-deployment-bucket

```
plugins:
  - serverless-deployment-bucket
provider:
  deploymentBucket:
    name: acme-stac-server-serverless-deployment
    blockPublicAccess: true
```
